// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/merchant": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/admin" | "/merchant";
  };
  "routes/index.jsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.jsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/admin/adminCenter.jsx": {
    id: "routes/admin/adminCenter";
    page: "/admin";
  };
  "routes/merchant/merchantCenter.jsx": {
    id: "routes/merchant/merchantCenter";
    page: "/merchant";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/index": typeof import("./app/routes/index.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
  "routes/register": typeof import("./app/routes/register.jsx");
  "routes/admin/adminCenter": typeof import("./app/routes/admin/adminCenter.jsx");
  "routes/merchant/merchantCenter": typeof import("./app/routes/merchant/merchantCenter.jsx");
};